add_newline = false

format = '''[\[](#6272a4)$fill$directory$fill[\]](#6272a4)
[\[](#6272a4)$username[@](#6272a4)$hostname[\]$git_branch](#6272a4)$character'''

right_format = ""

[username]
format = '[$user]($style)'
style_user = '#bd93f9'
style_root = '#ff5555'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = '#bd93f9'

[directory]
format = '[$path](#50fa7b)'
style = '#6272a4'
truncation_length = 0
truncation_symbol = ".../"
truncate_to_repo = false

[character]
format = '\$ '

[fill]
symbol = '.'
style = '#50fa7b'

[git_branch]
format = " [$symbol$branch]($style) "

